"""empty message

Revision ID: 4de6c4552f7c
Revises: bd57bae2bbb3
Create Date: 2021-03-02 14:16:49.703337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de6c4552f7c'
down_revision = 'bd57bae2bbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'client', 'user', ['user_id'], ['id'])
    op.drop_index('ix_client_family_client_family_phone', table_name='client_family')
    op.drop_column('client_family', 'client_family_phone')
    op.drop_index('ix_user_user', table_name='user')
    op.create_index(op.f('ix_user_user'), 'user', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user'), table_name='user')
    op.create_index('ix_user_user', 'user', ['user'], unique=1)
    op.add_column('client_family', sa.Column('client_family_phone', sa.INTEGER(), nullable=True))
    op.create_index('ix_client_family_client_family_phone', 'client_family', ['client_family_phone'], unique=1)
    op.drop_constraint(None, 'client', type_='foreignkey')
    # ### end Alembic commands ###
