"""Create db

Revision ID: ac7eab643e37
Revises: 
Create Date: 2021-02-24 15:17:36.664277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7eab643e37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_phone', sa.Integer(), nullable=True),
    sa.Column('client_birthday', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_client_birthday'), 'client', ['client_birthday'], unique=True)
    op.create_index(op.f('ix_client_client_name'), 'client', ['client_name'], unique=True)
    op.create_index(op.f('ix_client_client_phone'), 'client', ['client_phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_client_phone'), table_name='client')
    op.drop_index(op.f('ix_client_client_name'), table_name='client')
    op.drop_index(op.f('ix_client_client_birthday'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
