"""empty message

Revision ID: b8b5df2ebf46
Revises: 4de6c4552f7c
Create Date: 2021-03-02 14:19:51.510840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b5df2ebf46'
down_revision = '4de6c4552f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user'), 'user', ['user'], unique=False)
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_phone', sa.Integer(), nullable=True),
    sa.Column('client_birthday', sa.DateTime(), nullable=True),
    sa.Column('client_registration', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_client_birthday'), 'client', ['client_birthday'], unique=False)
    op.create_index(op.f('ix_client_client_name'), 'client', ['client_name'], unique=False)
    op.create_index(op.f('ix_client_client_phone'), 'client', ['client_phone'], unique=True)
    op.create_index(op.f('ix_client_client_registration'), 'client', ['client_registration'], unique=False)
    op.create_table('client_family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_family_name', sa.String(), nullable=True),
    sa.Column('client_family_birthday', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_family_client_family_birthday'), 'client_family', ['client_family_birthday'], unique=False)
    op.create_index(op.f('ix_client_family_client_family_name'), 'client_family', ['client_family_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_family_client_family_name'), table_name='client_family')
    op.drop_index(op.f('ix_client_family_client_family_birthday'), table_name='client_family')
    op.drop_table('client_family')
    op.drop_index(op.f('ix_client_client_registration'), table_name='client')
    op.drop_index(op.f('ix_client_client_phone'), table_name='client')
    op.drop_index(op.f('ix_client_client_name'), table_name='client')
    op.drop_index(op.f('ix_client_client_birthday'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_user_user'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
