"""add relationship for client

Revision ID: c20a3fc64037
Revises: d48c4e059de3
Create Date: 2021-03-02 12:27:29.397716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20a3fc64037'
down_revision = 'd48c4e059de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client', 'user', ['user_id'], ['id'])
    op.drop_index('ix_user_user', table_name='user')
    op.create_index(op.f('ix_user_user'), 'user', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user'), table_name='user')
    op.create_index('ix_user_user', 'user', ['user'], unique=1)
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'user_id')
    # ### end Alembic commands ###
