"""ДОбавили в юзер дату создания

Revision ID: d48c4e059de3
Revises: dcbf49c92328
Create Date: 2021-02-27 13:44:57.360219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48c4e059de3'
down_revision = 'dcbf49c92328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_on')
    # ### end Alembic commands ###
